// <auto-generated />
using System;
using InnoClinic.Services.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InnoClinic.Services.Infrastructure.Migrations
{
    [DbContext(typeof(ServicesDbContext))]
    partial class ServicesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InnoClinic.Services.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("765da283-1779-4aea-909d-f7a5ba6b32bc"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Price = 1500m,
                            ServiceName = "Первичный прием кардиолога",
                            SpecializationId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("ae484f68-911e-46bb-82ad-7daf45a54adb"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Price = 1700m,
                            ServiceName = "Прием невролога",
                            SpecializationId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("1523b195-ffa8-4457-844b-3899d5d38b25"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Price = 2500m,
                            ServiceName = "УЗИ сердца"
                        },
                        new
                        {
                            Id = new Guid("f4cd5bb7-5238-44aa-8fd5-181c27cda78b"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Price = 500m,
                            ServiceName = "Общий анализ крови"
                        });
                });

            modelBuilder.Entity("InnoClinic.Services.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSlotSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryName = "consultations",
                            TimeSlotSize = 30
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoryName = "diagnostics",
                            TimeSlotSize = 60
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CategoryName = "analyses",
                            TimeSlotSize = 15
                        });
                });

            modelBuilder.Entity("InnoClinic.Services.Domain.Entities.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            SpecializationName = "Кардиология"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsActive = true,
                            SpecializationName = "Неврология"
                        });
                });

            modelBuilder.Entity("InnoClinic.Services.Domain.Entities.Service", b =>
                {
                    b.HasOne("InnoClinic.Services.Domain.Entities.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnoClinic.Services.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Services")
                        .HasForeignKey("SpecializationId");

                    b.Navigation("Category");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("InnoClinic.Services.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("InnoClinic.Services.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
