// <auto-generated />
using System;
using InnoClinic.Profiles.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InnoClinic.Profiles.Infrastructure.Migrations
{
    [DbContext(typeof(ProfilesDbContext))]
    partial class ProfilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InnoClinic.Profiles.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CareerStartYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb22bb22-2222-2222-2222-222222222222"),
                            AccountId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CareerStartYear = 2018,
                            DateOfBirth = new DateTime(1990, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Alex",
                            LastName = "Petrov",
                            MiddleName = "Nikolaevich",
                            OfficeAddress = "Minsk, office 405",
                            SpecializationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "At work"
                        },
                        new
                        {
                            Id = new Guid("cc33cc33-3333-3333-3333-333333333333"),
                            AccountId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CareerStartYear = 2005,
                            DateOfBirth = new DateTime(1978, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Olga",
                            LastName = "Ivanova",
                            MiddleName = "Mikhailovna",
                            OfficeAddress = "Minsk, office 302",
                            SpecializationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "On vacation"
                        },
                        new
                        {
                            Id = new Guid("dd44dd44-4444-4444-4444-444444444444"),
                            AccountId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CareerStartYear = 2012,
                            DateOfBirth = new DateTime(1985, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Alex",
                            LastName = "Smith",
                            MiddleName = "John",
                            OfficeAddress = "Minsk, office 210",
                            SpecializationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "At work"
                        });
                });

            modelBuilder.Entity("InnoClinic.Profiles.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLinkedToAccount")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AccountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Emily",
                            IsLinkedToAccount = true,
                            LastName = "Brown",
                            MiddleName = "Grace",
                            Phone = "+1234567890",
                            PhotoUrl = "https://example.com/photos/emilybrown.jpg"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DateOfBirth = new DateTime(1988, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "James",
                            IsLinkedToAccount = false,
                            LastName = "Wilson",
                            Phone = "+10987654321"
                        });
                });

            modelBuilder.Entity("InnoClinic.Profiles.Domain.Entities.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SpecializationName = "Therapist"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            SpecializationName = "Surgeon"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            SpecializationName = "Cardiologist"
                        });
                });

            modelBuilder.Entity("InnoClinic.Profiles.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("InnoClinic.Profiles.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("InnoClinic.Profiles.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
